import Head from 'next/head';
import styled from 'styled-components';
import Pokemon from '../components/pokemon/pokemon';

const HeadingStyled = styled.h2`
  color: red;
`;

const MainStyled = styled.main`
  max-inline-size: 1100px;
  margin: auto;
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pokemon APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball-icon.png" />
      </Head>

      <MainStyled>
        <Pokemon />
      </MainStyled>
    </div>
  );
}
