import Head from 'next/head';
import styled from 'styled-components';
import Pokemon from '../components/pokemon/pokemon';

const MainStyled = styled.main`
  max-inline-size: 1400px;
  min-block-size: 100vh;
  margin: auto;
  @media screen and (min-width: 768px) {
    display: flex;
    align-items: center;
  }
`;

export default function Home() {
  return (
    <div>
      <Head>
        <title>Pokemon APP</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/pokeball-icon.png" />
      </Head>

      <MainStyled>
        <Pokemon />
      </MainStyled>
    </div>
  );
}
